In [1]:
!pip install -q geopandas
import geopandas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [15]:
df = pd.read_csv("visu_data.csv")
#import NY map file
boros = geopandas.read_file(geopandas.datasets.get_path("nybb"))

In [16]:
df.head()

,id,summary,house_rules,host_response_rate,neighbourhood_group_cleansed,room_type,accommodates,bathrooms,bedrooms,beds,...,Bronx,Staten_Island,Entire home,Private_room,Shared_room,flexible,moderate,strict_14,strict_30,strict
0,2595,"Find your romantic getaway to this beautiful, ...","Make yourself at home, respect the space and t...",90%,Manhattan,Entire home/apt,2,1.0,0.0,1.0,...,0,0,1,0,0,0,0,1,0,0
1,5099,My large 1 bedroom apartment is true New York ...,• Check-in time is 2PM. • Check-out time is 12...,90%,Manhattan,Entire home/apt,2,1.0,1.0,1.0,...,0,0,1,0,0,0,0,1,0,0
2,5222,N,Please let me know if you will be staying with...,100%,Manhattan,Entire home/apt,2,1.0,1.0,1.0,...,0,0,1,0,0,0,0,1,0,0
3,5238,"Live like a New Yorker instead of a stuffy, ti...",No smoking in apartment. No Pets allowed. Ple...,100%,Manhattan,Entire home/apt,3,1.0,1.0,2.0,...,0,0,1,0,0,0,0,1,0,0
4,5295,N,"Dear Guests, Welcome to my apartment and I hop...",100%,Manhattan,Entire home/apt,2,1.0,1.0,1.0,...,0,0,1,0,0,0,0,1,0,0

In [11]:
# find the average price each neighbourhood group
fdf = df.groupby("neighbourhood_group_cleansed")['price'].mean().reset_index()
# sort_values() does not change the index of the rows, reset_index() is used to fix this, making sure Borough index is same
Boros = boros.sort_values(by=['BoroName'], ascending = True).reset_index()
fdf.price = round(fdf.price)
fdf

DataError: No numeric types to aggregate